#!/bin/sh -e

patch -p1 < fix-75-yes-terminus.patch

./configure \
	--prefix=/usr \
	--x11dir=/usr/share/fonts/misc \
	--otbdir=/usr/share/fonts/misc \
	--psfdir=/usr/share/kbd/consolefonts \

make all otb

make DESTDIR="$1" install install-otb
install -Dm644 75-yes-terminus.conf "$1/etc/fonts/conf.avail/75-yes-terminus.conf"
install -Dm644 OFL.TXT "$1/usr/share/licenses/terminus-font/LICENSE"
install -d "$1/etc/fonts/conf.d"

cd "$1/etc/fonts/conf.d"
ln -s ../conf.avail/75-yes-terminus.conf


