#!/bin/sh -e
ls

cd runit-2.1.2/src

sed -e 's,sbin/runit,usr/bin/runit,g' -i runit.h

echo "gcc $CFLAGS" > conf-cc
echo "gcc $LDFLAGS -Wl,-z -Wl,noexecstack" > conf-ld

sed -i -e 's:^char \*varservice = "/service/";$:char \*varservice ="/var/service/";:' sv.c

sed -i -e 's:short x\[4\];$:gid_t x[4];:' chkshsgr.c

make

mkdir -p "$1/var"
ln -s ../run/runit/runsvdir/current "$1"/var/service

mkdir -p "$1/usr/bin"
for f in chpst runit runit-init runsv runsvchdir runsvdir sv svlogd utmpset; do
	cp "$f" "$1/usr/bin"
done

